### ISSUE TITLE
启动fe的时候系统报错：unsupport orm tag user_name

### ISSUE THREAD

**Issue by jetgeng** [Cepave/open-falcon-backend#131]
## 操作步骤
 * 编译代码。
 * 修改fe的配置文件，将数据连接都配置正确。
 * 运行  ./open-falcon start fe

## 期望结果
falcon-fe启动成功。

## 结果

```
time="2016-09-28T08:43:14-04:00" level=info msg="read config file: /root/bin/fe/config/cfg.json successfully"
[ORM]2016/09/28 08:43:14 unsupport orm tag user_name
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4950a8]

goroutine 1 [running]:
panic(0xd1bd20, 0xc820012120)
panic(0xd1bd20, 0xc820012120)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/Cepave/open-falcon-backend/modules/fe/model.InitDatabase()
        /root/.goPath/src/github.com/Cepave/open-falcon-backend/modules/fe/model/database.go:24 +0x718
main.main()
        /root/Download/open-falcon-backend/modules/fe/main.go:41 +0x2bd
```
通过出错代码判断是： Cepave/open-falcon-backend/modules/fe/model/database.go 这个地方出错了。

**Comment by jetgeng** [comment]
我阅读了这个代码. 发现加上了boss这个数据库配置。
```
orm.RegisterDataBase("boss", "mysql", config.BossDB.Addr, config.BossDB.Idle, config.BossDB.Max)
```
但是在配置文件中，这个boss相关的数据配置没有存在。

**Comment by hitripod** [comment]
谢谢，已合并

**Comment by jetgeng** [comment]
谢谢！
